Store IP addresses as str
When getting the IP addresses from the region server,
we were storing IPv4Address and IPv6Addresses types

When we do the socket connection with that it fails

```
connection = socket.create_connection((server_ip, 443), timeout=2)
  File "/usr/lib64/python3.4/socket.py", line 498, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.4/socket.py", line 537, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
TypeError: getaddrinfo() argument 1 must be string or None
```

Update integration test process

This is a follow up fix to commit 33f585c

This Fixes bsc#1247466