Show LTSS activation error in the terminal
for example
> registercloudguest --regcode WRONG-CODE
Running LTSS registration...this takes a little longer
Error: Registration server returned 'The subscription with
registration code 'WRONG-CODE' does not include the requested product
'SUSE Linux Enterprise Server LTSS 15 SP5 x86_64'' (422)
LTSS registration failed see /var/log/cloudregister for details

This fixes bsc#1258026